"""empty message

Revision ID: 922b6e25b104
Revises: 40f21243bfeb
Create Date: 2021-08-21 10:10:08.785874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922b6e25b104'
down_revision = '40f21243bfeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('favorite', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorite', 'planet', ['planet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_column('favorite', 'planet_id')
    op.drop_table('planet')
    # ### end Alembic commands ###
